
project_name: noderesolver-aws

builds:
  - main: aws.go
    binary: plugin/server/noderesolver-aws
    goos:
      - linux
    goarch:
      - amd64

archive:
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  # wrap_in_directory: true
  replacements:
    amd64: x86_64

