sudo: false
dist: trusty

language: go

cache:
    directories:
        - .cache

script:
    - ./build.sh setup
    - ./build.sh deps
    - ./build.sh protobuf_verify
    - ./build.sh binaries
    - ./build.sh test
