version: 2

jobs:
  build:
    machine: true
    working_directory: ~/go/src/github.com/spiffe/node-agent
    steps:
      - checkout
      - restore_cache:
          key: v1-{{ checksum "build_setup.sh" }}{{ checksum "glide.lock" }}
      - run: make setup
      - run: make build
      - run: make test
      - store_test_results:
          path: .test_results
      - save_cache:
          key: v1-{{ checksum "build_setup.sh" }}{{ checksum "glide.lock" }}
          paths:
            - .cache
